#Фильтр на сообщения будет срабатывать только если игрок ввел команду, указаную в triggercommands
#Рекомендации по оптимизации:
#Персоналу сервера выдать право satanicfilter.ignore Для того, что бы не делать лишние проверки.
#Очищать файл с логами каждый месяц. Логи сохраняются в отдельном потоке, что предотвращает потерю стабильности сервера, но удалять логи - хорошая практика.
#Команда для перезагрузки конфига(Обновления запрещеных слов) /sFilter reload
#Добавление новых слов:
#Слова записываются через знак | Первое слово - то, которое нужно заменить. Второе слово то, на которое будет заменено.
#Регистр игнорируется. Т.е если первое слово будет cock то если игрок напишет слово CoCk - то все равно слово заменится
#Так же поддерживается мульти-слова.
#Например 'fuck you|love you' - в данном случае, если игрок напишет fuck you - то в сообщении будет заменено на love you т.к плагин ищет точное совпадение по строке.
#
#
triggercommands:
  - /msg
  - /tell
  - /r
  - /m
blacklist:
  - 'сука|с*ка'
  - 'fuck|f*ck'
  - 'блядь|б*лядь'
  - 'пизда|п*зда'
  - 'шалава|ш*лава'
  - 'хуй|х*й'
  - 'dick|d*ck'
  - 'slut|s*ut'
  - 'cock|c*ck'
  - 'fuck you|love you'