name: ChatFilter
version: '${project.version}'
main: org.mrdarkimc.chatfilter.ChatFilter
description: Плагин на заказ на фильтрование команд и табличек.
api-version: '1.19'
author: MrDarkiMC
website: https://kwork.ru/user/mrdarkimc
softdepend:
  - ChatEx
permissions:
  satanicfilter.ignore:
    description: Игнорирует проверки.
    default: false
  satanicfilter.chatmoderator:
    description: Позволяет игроку получать сообщения для модерации
    default: false
commands:
  sfilter:
    usage: /sFilter reload
