#Фильтр на сообщения будет срабатывать только если игрок ввел команду, указаную в triggercommands
#Рекомендации по оптимизации:
#Персоналу сервера выдать право satanicfilter.ignore Для того, что бы не делать лишние проверки.
#Очищать файл с логами каждый месяц. Логи сохраняются в отдельном потоке, что предотвращает потерю стабильности сервера, но удалять логи - хорошая практика.
#Команда для перезагрузки конфига(Обновления запрещеных слов) /sFilter reload
#Добавление новых слов:
#Слова записываются через знак | Первое слово - то, которое нужно заменить. Второе слово то, на которое будет заменено.
#Регистр игнорируется. Т.е если первое слово будет cock то если игрок напишет слово CoCk - то все равно слово заменится
#Так же поддерживается мульти-слова.
#Например 'fuck you|love you' - в данном случае, если игрок напишет fuck you - то в сообщении будет заменено на love you т.к плагин ищет точное совпадение по строке.
#
#
#Сообщение будет проверяться на наличие слов из banlist игнорируя ignoreChar
#Т.е если сообщение: "заходите на f u n t i m e" -> то оно не пройдет т.к в ignoreChar есть символ пробела
#сообщение "Заходите на no-name.ru" не пройдет, т.к в ignoreChar нет символа точки
# "заходите на server точка ru" тоже не пройдет, т.к "точка" заменяется на "." и уже потом проверяется домен
URL: "https://funmine.su/admin/chat_bot.php"
servername: "Анархия-1"
ignoreChar: ' &?<>,.1234567890!~[]`-\|/~()+='
newbiePlayTimeInTicks: 12000 #10 минут в тиках. (10 * 20 * 60 = 12000)
mutecommand: 'tempipmute {player} {args}' #после этого будет добавлены аргументы
messages:
  banmessage:
    enable: true
    text:
      - ' '
      - '  &c&l| &#D27E7EВаше сообщение похоже на рекламу и отправлено на модерацию. Ожидайте одобрения, или бана.'
      - ' '
  player_left:
    enable: true
    text:
      - ' '
      - '  &c&l| &#D27E7EИгрок {player} не имеет чат-ограничений. Возможно он вышел с сервера.'
      - ' '
  already_banmessage:
    enable: true
    text:
      - ' '
      - '  &c&l| &#D27E7EВаше сообщение все еще похоже на рекламу.'
      - '  &c&l| &#D27E7EПредыдущее сообщение уже рассматривается модераторами'
      - ' '
  player_passed: #Всем у кого есть право satanicfilter.chatmoderator
    enable: true
    text:
      - ' '
      - '  &a&l| &#7EBC82Сообщение игрока {player} одобрено'
      - ' '
  playtime: #Всем у кого есть право satanicfilter.chatmoderator
    enable: true
    text:
      - ' '
      - '  &c&l| &#D27E7EВы не достаточно наиграли, что бы писать в чат.'
      - ' '
  playerPassed:
    enable: true
    text:
      - ' '
      - '  &a&l| &#7EBC82Ваше сообщение одобрено'
      - '  &a&l| &#7EBC82Приносим извинения'
      - ' '
  player_muted: #Всем у кого есть право satanicfilter.chatmoderator
    enable: true
    text:
      - ' '
      - '  &a&l| &#7EBC82Сообщение игрока {player} привело к муту'
      - ' '
banlist:
  - "rushtime"
  - "funtrain"
  - "funtrаin"
  - "metahvh"
  - "world"
  - "wоrld"
  - "legendagrief"
  - "reallyworld"
  - "domerl"
  - "точкаru"
  - "точкаsu"
  - "точкаcom"
  - "точкаlol"
  - "точкаru"
  - "точкаnet"
  - "точкаtech"
  - "discordgg"
  - "tiktokcom"
  - "twitchtv"
  - "vkcom"
  - "funpaycom"
  - "youtubecom"
  - "allзаходитена"
  - "аллзаходитена"
  - "халявныерилики"
  - "всембесплатныйдонат"
  - "лучшаякопияхо"
  - "лучшаякопияфан"
  - "лучшаякопияри"
  - "лучшаякопияre"
  - "лучшаякопияho"
  - "лучшаякопияfu"
  - "лучшиюкопиюхо"
  - "лучшиюкопиюфан"
  - "лучшиюкопиюre"
  - "лучшиюкопиюho"
  - "лучшиюкопиюfu"
  - "ищитехорошийсервер"
  - "ищитесерверс"
  - "ищитеserverс"
  - "ищитеservers"
  - "заходискорее"
  - "давноискаллучшийхвх"
  - "тогдатебена"
  - "открылсяновыйпр"
  - "открылсяновыйсе"
  - "открылсяновыйгри"
  - "открылсяновыйана"
  - "лучшийанархичиск"
  - "лучшийгриферс"
  - "новогопокаления"
  - "минимальнаясуммадляигры"
  - "заходитеналучшуюкопию"
  - "зах0дитена"
  - "балансботанаданный"
  - "серверновогоп"
  - "открылсяновыйсервер"
  - "открылсяновыйпрое"
  - "заходитенанов"
  - "ищешьанархию"
  - "покоманде"
  - "ddosby"
triggercommands:
  - /msg
  - /tell
  - /r
  - /m
  - /cmi msg
  - /cmi message
  - /bc
  - /broadcast
  - /cmi broadcast
  - /cmi bc
  - /rename
  - /cmi rename
blacklist:
  - 'сеpв|****'
  - 'сеpв|****'
  - 'cеpв|****'
  - 'cepв|****'
  - 'сepв|****'
  - 'cepв|****'
  - 'cepв|****'
  - 'серв|****'
  - '-уя|-ez'
  - '-уя|-ez'
  - 'сука|с*ка'
  - 'fuck|f*ck'
  - 'шалава|шал*ва'
  - 'хуём|ху*м'
  - 'сук|с*к'
  - 'fuck|f*ck'
  - 'бля|б*я'
  - 'пизд|п*зд'
  - 'пидр|п*др'
  - 'хуита|х*ита'
  - 'хуета|х*ета'
  - 'хуес|х*ес'
  - 'член|чл*н'
  - 'бляд|бл*д'
  - 'еблан|е*л*н'
  - 'хyй|х*й'
  - 'xyй|х*й'
  - 'хуй|х*й'
  - 'порн|п*рн'
  - 'уебок|у*бок'
  - 'уёбок|у*бок'
  - 'заеб|за*б'
  - 'заиб|за*б'
  - 'ебал|еб*л'
  - 'негр|н*гр'
  - 'нигер|н*гер'
  - 'пидар|пи**р'
  - 'пидор|пи**р'
  - 'гитлер|ги*лер'
  - 'хохол|хо*ол'
  - 'охуеть|ох*еть'
  - 'долб|дол*'
  - 'далб|дол*'
  - 'ебу|еб*'
  - 'наци|нац*'
  - 'нацы|нац*'
  - 'хуи|ху*'
  - 'слава р|с***а р'
  - 'слава у|с***а у'
  - 'гойда|*****'
  - 'пенис|пенис'
  - 'охуе|ох*е'
  - 'ахуе|ах*е'
  - 'пида|п**а'
  - 'гандон|г***он'
  - 'шлюх|ш**х'
  - 'дроч|д**ч'
  - 'разъеб|раз*б'
  - 'подъеб|под*б'
  - 'перееб|пере*б'
  - 'долбоёб|долбо*б'
  - 'далбоёб|долбо*б'
  - 'далбаёб|долбо*б'
  - 'шлюха|шл**а'
  - 'залу|зал*'
  - 'захер|зах*р'
  - 'сперм|сп*рм'
  - 'твою мать|твою м*ть'
  - 'сын бл|с** бл'
  - 'в рот еб|в р** еб'
  - 'ебырь|е*ырь'
  - 'нассать|нас*ать'
  - 'нассоть|нас*ать'
  - 'пидорас|п*дорас'
  - 'пидарок|п*дарок'
  - 'ебанашка|е*анашка'
  - 'ебанутый|е*анутый'
  - 'хуевина|ху*вина'
  - 'пиздеть|п*здеть'
  - 'пиндосы|пи**осы'
  - 'насоса|на**са'
  - 'насаса|на**са'
  - 'маму|м**у'
  - 'сын бляд|с** бляд'
  - 'сын шл|с** шл'
  - 'сын праститу|с** пр*ститу'
  - 'сын проститу|с** пр*ститу'
  - 'уебанище|у*банище'
  - 'гонд|го*д'
  - 'ганд|го*д'
  - 'ахуел|а*уел'
  - 'пенис|п*нис'
  - 'мать|м*ть'
  - 'сын бездар|с** бездар'
  - 'сын шлюх|с** шлюх'
  - 'еба|еб*'
  - 'ебли|еб*и'
  - 'уеба|у*ба'
  - 'уебищ|у*бищ'
  - '\\.mc|*'
  - 'mc\\.|*'
  - 'серв хуйни|лучший сервер'
  - 'маму|м**у'
  - 'мамаш|****'
  - 'нурсултан бустит|нурик говно'
  - 'нурик бустит|нурик говно'
  - 'нурик буст|нурик говно'
  - 'кфг броя|*'
  - 'кфг броя|*'
  - 'нурсултан|*'
  - 'cэкс|c*кс'
  - 'cекс|c*кс'
  - 'сиськи|с*с*ки'
  - 'нурик|*'
  - 'нyрик|*'
  - 'hyрик|*'
  - 'нyриk|*'
  - 'hyриk|*'
  - 'nursultan|*'
  - 'expensive|*'
  - 'экспа|*'
  - 'экспы|*'
  - 'deadcode|*'
  - 'meteor|*'
  - 'delta|*'
  - 'хуй|х*й'
  - 'хyй|х*й'
